version: "3.8"

services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    volumes:
      - backend-data:/app/data

  frontend:
    build:
      context: ./FrontEnd
      args:
        # VITE_USER_END_POINT: http://backend:3000/user
        VITE_ORIGINAL_BASE_URL: http://backend:3000
        VITE_GOOGLE_API_KEY: AIzaSyDEbHkHFIiE3qzl_iDrXw3XXLUZ7Oy5lh0
        VITE_GOOGLE_API_URL: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend